"""Which Codex entries still open straight on a section heading.

A tester read the Codex as too technical for a new player: entries that begin
on a <color=Caption> heading give the reader a rule before telling them what
the topic is for. This lists the entries that still do, worst first, so leads
can be added a bucket at a time. Re-run after editing entries:

    py docs/codex-entry-leads.py

Output: docs/codex-entry-leads.md (fully generated - do not hand-edit).

"Opens" means the ENG body's first character is a <color=Caption> tag. Entries
already carrying a lead sentence are listed separately at the bottom so the
count can be checked at a glance.
"""
import io, os, re
from collections import defaultdict

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
gametext = os.path.join(root, "game", "Content", "GameText.yaml")
codexyaml = os.path.join(root, "game", "Content", "Codex.yaml")
hooksyaml = os.path.join(root, "game", "Content", "CodexHooks.yaml")
outpath = os.path.join(root, "docs", "codex-entry-leads.md")


def read(path):
    """Text of a content yaml, line endings normalised.

    GameText.yaml is CRLF on disk and the others are LF, but that depends on
    .gitattributes and core.autocrlf. Splitting on a hard-coded "\\r\\n" would
    silently yield a single line, and this script would report zero entries
    rather than fail, so normalise instead.
    """
    return io.open(path, "rb").read().decode("utf-8-sig").replace("\r\n", "\n")


# --- GameText: Codex*Text bodies and their sibling *Short one-liners ---------
bodies, shorts = {}, {}
lines = read(gametext).split("\n")
for i, line in enumerate(lines):
    m = re.match(r"^(Codex\w+?)(Text|Short):\s*$", line)
    if not m:
        continue
    for j in range(i + 1, min(i + 6, len(lines))):
        me = re.match(r'^\s*ENG:\s*"(.*)"\s*$', lines[j])
        if me:
            (bodies if m.group(2) == "Text" else shorts)[m.group(1)] = me.group(1)
            break

# --- Codex.yaml: UID -> token name, and the bucket (top-level UID) it sits in -
uid_of, bucket_of = {}, {}
bucket = None
for line in read(codexyaml).split("\n"):
    m = re.match(r"^(\s*)UID:\s*(\S+)\s*$", line)
    if not m:
        continue
    indent, uid = len(m.group(1)), m.group(2)
    if indent <= 2:
        bucket = uid
    token = "Codex" + "".join(p.capitalize() for p in uid.split("_"))
    uid_of[token] = uid
    bucket_of[token] = bucket or uid

# --- CodexHooks.yaml: how many tooltips point at each entry ------------------
hooks = defaultdict(int)
for line in read(hooksyaml).split("\n"):
    m = re.match(r"^\s*(\w+)\s*:\s*(\S+)\s*$", line)
    if m and not line.lstrip().startswith("#"):
        hooks[m.group(2)] += 1

# --- classify ---------------------------------------------------------------
needs, have = [], []
for token, body in sorted(bodies.items()):
    uid = uid_of.get(token, "")
    row = {
        "token": token,
        "uid": uid,
        "bucket": bucket_of.get(token, ""),
        "chars": len(body),
        "sections": body.count("<color=Caption>"),
        "bullets": body.count("<li>"),
        "hooks": hooks.get(uid, 0),
        "short": shorts.get(token, "").strip(),
    }
    (needs if body.startswith("<color=Caption>") else have).append(row)

# worst first: the entries players reach most, then the densest
needs.sort(key=lambda r: (-r["hooks"], -r["sections"], -r["chars"]))

out = []
out.append("# Codex entries still missing a lead\n")
out.append(
    "Generated by `docs/codex-entry-leads.py`. Do not hand-edit.\n\n"
    "An entry that opens on a `<color=Caption>` heading hands the reader a rule before saying what "
    "the topic is for. The fix is one to three plain sentences at the top, before the first heading: "
    "what this is and why the player cares, no numbers. Adding one is purely additive: no already "
    "fact-checked sentence moves, so nothing needs re-verifying. Keep the lead claim-free where you "
    "can, and check it against the code like any other entry where you cannot.\n\n"
    "A second, optional pass is worth doing once the leads are in: move per-ship-type variants, "
    "exceptions and interactions out of the opening paragraph, and let the shape vary between "
    "entries, because uniform structure is what reads as machine-written. That pass does move "
    "verified text, so re-read whatever you move.\n\n"
    "**Order:** most tooltip hooks first (a proxy for how often a player lands there), then the "
    "densest. Do a bucket at a time and get a tester's read before continuing.\n")
out.append("Entries: %d. Missing a lead: %d. Already have one: %d.\n"
           % (len(bodies), len(needs), len(have)))
out.append("| # | Entry | Bucket | Hooks | Chars | Sections | Bullets | What it covers |")
out.append("|---|---|---|---|---|---|---|---|")
for n, r in enumerate(needs, 1):
    out.append("| %d | `%s` | %s | %d | %d | %d | %d | %s |"
               % (n, r["uid"] or r["token"], r["bucket"], r["hooks"],
                  r["chars"], r["sections"], r["bullets"], r["short"].replace("|", "\\|")))

out.append("\n## Already carry a lead\n")
out.append("Left alone. Listed so the totals can be checked.\n")
out.append("| Entry | Bucket | Chars |")
out.append("|---|---|---|")
for r in sorted(have, key=lambda r: (r["bucket"], r["uid"])):
    out.append("| `%s` | %s | %d |" % (r["uid"] or r["token"], r["bucket"], r["chars"]))

io.open(outpath, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print("wrote %s" % outpath)
print("%d entries: %d need a lead, %d already have one" % (len(bodies), len(needs), len(have)))
