// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable CommentTypo
namespace Ship_Game
{
    /// <summary>
    /// This file was auto-generated by SDGameTextToEnum.exe
    /// </summary>
    public enum GameTips
    {
        /// <summary>Attack Runs Order</summary>
        AttackRunsOrder = 1,
        /// <summary>Artillery Order</summary>
        ArtilleryOrder = 2,
        /// <summary>Orbit Left Order</summary>
        OrbitLeftOrder = 3,
        /// <summary>Orbit Right Order</summary>
        OrbitRightOrder = 4,
        /// <summary>Maintain Order</summary>
        MaintainOrder = 5,
        /// <summary>Evade Order</summary>
        EvadeOrder = 6,
        /// <summary>Assist Slider</summary>
        AssistSlider = 7,
        /// <summary>Defender Slider</summary>
        DefenderSlider = 8,
        /// <summary>Vulture Slider</summary>
        VultureSlider = 9,
        /// <summary>Armor Slider</summary>
        ArmorSlider = 10,
        /// <summary>Shielded Slider</summary>
        ShieldedSlider = 11,
        /// <summary>DPS Slider</summary>
        DpsSlider = 12,
        /// <summary>Operational Radius</summary>
        OperationalRadius = 13,
        /// <summary>Size Slider</summary>
        SizeSlider = 14,
        /// <summary>Define AO</summary>
        DefineAo = 15,
        /// <summary>Trade Food</summary>
        TradeFood = 16,
        /// <summary>Trade Production</summary>
        TradeProduction = 17,
        /// <summary>Send_Troops_Supply</summary>
        ShieldToggle = 18,
        /// <summary>Launch Fighters</summary>
        LaunchFighters = 19,
        /// <summary>Food Icon</summary>
        FoodIcon = 20,
        /// <summary>Production Icon</summary>
        ProductionIcon = 21,
        /// <summary>Research Icon</summary>
        ResearchIcon = 22,
        /// <summary>Ore Icon</summary>
        OreIcon = 23,
        /// <summary>Mark for Colonization</summary>
        MarkForColonization = 24,
        /// <summary>UnMark for Colonization</summary>
        UnmarkForColonization = 25,
        /// <summary>Flag indicating marked</summary>
        FlagIndicatingMarked = 26,
        /// <summary>Ship Selector Power</summary>
        ShipSelectorPower = 27,
        /// <summary>Ship Selector Shields</summary>
        ShipSelectorShields = 28,
        /// <summary>Ship Selector Ordnance</summary>
        ShipSelectorOrdnance = 29,
        /// <summary>Ship Selector Defense</summary>
        ShipSelectorDefense = 30,
        /// <summary>Planet Selector Defense</summary>
        PlanetSelectorDefense = 31,
        /// <summary>orbital asset bombard</summary>
        OrbitalAssetBombard = 32,
        /// <summary>unit defense</summary>
        UnitDefense = 33,
        /// <summary>soft attack</summary>
        SoftAttack = 34,
        /// <summary>hard attack</summary>
        HardAttack = 35,
        /// <summary>land troops button</summary>
        LandTroopsButton = 36,
        /// <summary>ship troop capacity</summary>
        ShipTroopCapacity = 37,
        /// <summary>Intelligence Penetration</summary>
        IntelligencePenetration = 38,
        /// <summary>Intelligence Budget</summary>
        IntelligenceBudget = 39,
        /// <summary>Counterspy Budget</summary>
        CounterspyBudget = 40,
        /// <summary>Plant mole</summary>
        PlantMole = 41,
        /// <summary>Discover Plot</summary>
        DiscoverPlot = 42,
        /// <summary>damage relations</summary>
        DamageRelations = 43,
        /// <summary>Plant saboteur</summary>
        PlantSaboteur = 44,
        /// <summary>activate saboteur</summary>
        ActivateSaboteur = 45,
        /// <summary>steal technology</summary>
        StealTechnology = 46,
        /// <summary>trust</summary>
        Trust = 47,
        /// <summary>anger</summary>
        Anger = 48,
        /// <summary>fear</summary>
        Fear = 49,
        /// <summary>Rush Production</summary>
        RushProduction = 50,
        /// <summary>Add to Q</summary>
        AddToQ = 51,
        /// <summary>Edit ship</summary>
        EditShip = 52,
        /// <summary>Cancel Production</summary>
        CancelProduction = 53,
        /// <summary>DSBW</summary>
        Dsbw = 54,
        /// <summary>Ships List</summary>
        ShipsList = 55,
        /// <summary>Planets List</summary>
        PlanetsList = 56,
        /// <summary>Home</summary>
        Home = 57,
        /// <summary>Zoom out</summary>
        ZoomOut = 58,
        /// <summary>Automation</summary>
        Automation = 59,
        /// <summary>Fleets</summary>
        Fleets = 60,
        /// <summary>View Planet</summary>
        ViewPlanet = 61,
        /// <summary>View Tactical</summary>
        ViewTactical = 62,
        /// <summary>Queue up</summary>
        QueueUp = 63,
        /// <summary>Queue down</summary>
        QueueDown = 64,
        /// <summary>Hold Position Order</summary>
        HoldPositionOrder = 65,
        /// <summary>Taxes</summary>
        Taxes = 66,
        /// <summary>Launch Troop</summary>
        LaunchTroop = 67,
        /// <summary>Experience</summary>
        Experience = 68,
        /// <summary>Lock</summary>
        Lock = 69,
        /// <summary>Food</summary>
        Food = 70,
        /// <summary>prod</summary>
        Prod = 71,
        /// <summary>Res</summary>
        Res = 72,
        /// <summary>prod</summary>
        Prod2 = 73,
        /// <summary>Res</summary>
        Res2 = 74,
        /// <summary>Population</summary>
        Population = 75,
        /// <summary>view colony</summary>
        ViewColony = 76,
        /// <summary>cybernetic food</summary>
        CyberneticFood = 77,
        /// <summary>delete design</summary>
        DeleteDesign = 78,
        /// <summary>ship mass</summary>
        ShipMass = 79,
        /// <summary>mod health</summary>
        ModHealth = 80,
        /// <summary>mod health</summary>
        ModHealth2 = 81,
        /// <summary>mod health</summary>
        ModHealth3 = 82,
        /// <summary>wpn damage</summary>
        WpnDamage = 83,
        /// <summary>mod cost</summary>
        ModCost = 84,
        /// <summary>proj speed</summary>
        ProjSpeed = 85,
        /// <summary>DPS</summary>
        Dps = 86,
        /// <summary>beam cps</summary>
        BeamCps = 87,
        /// <summary>field of fire</summary>
        FieldOfFire = 88,
        /// <summary>ord per shot</summary>
        OrdPerShot = 89,
        /// <summary>pwr per shot</summary>
        PwrPerShot = 90,
        /// <summary>thrust</summary>
        Thrust = 91,
        /// <summary>warp thrust</summary>
        WarpThrust = 92,
        /// <summary>shield hp</summary>
        ShieldHp = 93,
        /// <summary>shield rad</summary>
        ShieldRad = 94,
        /// <summary>shield regen</summary>
        ShieldRegen = 95,
        /// <summary>sensor range</summary>
        SensorRange = 96,
        /// <summary>repair rate</summary>
        RepairRate = 97,
        /// <summary>hangar</summary>
        Hangar = 98,
        /// <summary>ship cost</summary>
        ShipCost = 99,
        /// <summary>ship power</summary>
        ShipPower = 100,
        /// <summary>ship powerdraw</summary>
        ShipPowerdraw = 101,
        /// <summary>ship warp powerdraw</summary>
        ShipWarpPowerdraw = 102,
        /// <summary>total hp</summary>
        TotalHp = 103,
        /// <summary>shield hp</summary>
        ShieldHp2 = 104,
        /// <summary>speed sublight</summary>
        SpeedSublight = 105,
        /// <summary>speed warp</summary>
        SpeedWarp = 106,
        /// <summary>turn</summary>
        Turn = 107,
        /// <summary>ord</summary>
        Ord = 108,
        /// <summary>cargo</summary>
        Cargo = 109,
        /// <summary>emp</summary>
        Emp = 110,
        /// <summary>ascension</summary>
        Ascension = 111,
        /// <summary>sandbox</summary>
        Sandbox = 112,
        /// <summary>food carry</summary>
        FoodCarry = 113,
        /// <summary>prod carry</summary>
        ProdCarry = 114,
        /// <summary>colo carry</summary>
        ColoCarry = 115,
        /// <summary>EMP disabled</summary>
        EmpDisabled = 116,
        /// <summary>inhibited</summary>
        Inhibited = 117,
        /// <summary>boarding</summary>
        Boarding = 118,
        /// <summary>ground com</summary>
        GroundCom = 119,
        /// <summary>spy</summary>
        Spy = 120,
        /// <summary>anomaly</summary>
        Anomaly = 121,
        /// <summary>space combat</summary>
        SpaceCombat = 122,
        /// <summary>enemy here</summary>
        EnemyHere = 123,
        /// <summary>ord cap added</summary>
        OrdCapAdded = 124,
        /// <summary>scale</summary>
        Scale = 125,
        /// <summary>pacing</summary>
        Pacing = 126,
        /// <summary>troop level</summary>
        TroopLevel = 127,
        /// <summary>can't declare war peace treaty</summary>
        CantDeclareWarPeaceTreaty = 128,
        /// <summary>Non Aggression</summary>
        NonAggression = 129,
        /// <summary>open borders</summary>
        OpenBorders = 130,
        /// <summary>Peace Treaty</summary>
        PeaceTreaty = 131,
        /// <summary>trade Treaty</summary>
        TradeTreaty = 132,
        /// <summary>alliance Treaty</summary>
        AllianceTreaty = 133,
        /// <summary>fire arcs</summary>
        FireArcs = 134,
        /// <summary>Warp Speed</summary>
        WarpSpeed = 135,
        /// <summary>Explore</summary>
        Explore = 136,
        /// <summary>pass tran</summary>
        PassTran = 137,
        /// <summary>pass tran</summary>
        PassTran2 = 138,
        /// <summary>empire screen food</summary>
        EmpireScreenFood = 139,
        /// <summary>empire screen prod</summary>
        EmpireScreenProd = 140,
        /// <summary>empire screen res</summary>
        EmpireScreenRes = 141,
        /// <summary>empire screen money</summary>
        EmpireScreenMoney = 142,
        /// <summary>boarding defense</summary>
        BoardingDefense = 143,
        /// <summary>inhib</summary>
        Inhib = 144,
        /// <summary>power store max</summary>
        PowerStoreMax = 145,
        /// <summary>recall fighters</summary>
        RecallFighters = 146,
        /// <summary>vs armor</summary>
        VsArmor = 147,
        /// <summary>rot thrust</summary>
        RotThrust = 148,
        /// <summary>resupply</summary>
        Resupply = 149,
        /// <summary>empire defense</summary>
        EmpireDefense = 150,
        /// <summary>trade</summary>
        Trade = 151,
        /// <summary>trade</summary>
        Trade2 = 152,
        /// <summary>trade</summary>
        Trade3 = 153,
        /// <summary>ECM value</summary>
        EcmValue = 154,
        /// <summary>ECM Resistance value</summary>
        EcmResistanceValue = 155,
        /// <summary>Beam Duration</summary>
        BeamDuration = 156,
        /// <summary>Scrap Ship</summary>
        ScrapShip = 157,
        /// <summary>Refit Ship</summary>
        RefitShip = 158,
        /// <summary>Broadside Port</summary>
        BroadsidePort = 159,
        /// <summary>Broadside Starboard</summary>
        BroadsideStarboard = 160,
        /// <summary>New Experience</summary>
        NewExperience = 161,
        /// <summary>Ordance recovered per sec.</summary>
        OrdanceRecoveredPerSec = 162,
        /// <summary>Seconds until out of power or INFinite</summary>
        SecondsUntilOutOfPower = 163,
        /// <summary>Seconds until out of ordnance or INFinite</summary>
        SecondsUntilOutOfOrdnance = 164,
        /// <summary>Elimination Game mode</summary>
        EliminationGameMode = 165,
        /// <summary>Repair Beam</summary>
        RepairBeam = 166,
        /// <summary>Repair Beam</summary>
        RepairBeam2 = 167,
        /// <summary>Transporter Range</summary>
        TransporterRange = 168,
        /// <summary>Transporter Power</summary>
        TransporterPower = 169,
        /// <summary>Transporter Time</summary>
        TransporterTime = 170,
        /// <summary>Transporter Ordnance</summary>
        TransporterOrdnance = 171,
        /// <summary>Transporter Troop Landing</summary>
        TransporterTroopLanding = 172,
        /// <summary>Troop Capacity</summary>
        TroopCapacity = 173,
        /// <summary>Troop Heal</summary>
        TroopHeal = 174,
        /// <summary>Shipyard Upkeep</summary>
        ShipyardUpkeep = 175,
        /// <summary>FTL Timer</summary>
        FtlTimer = 176,
        /// <summary>FTL Spool</summary>
        FtlSpool = 177,
        /// <summary>Module power draw at warp</summary>
        ModulePowerDrawAtWarp = 178,
        /// <summary>Module troop capacity</summary>
        ModuleTroopCapacity = 179,
        /// <summary>Ship troop capacity</summary>
        ShipTroopCapacity2 = 180,
        /// <summary>Weapon Shield Pen</summary>
        WeaponShieldPen = 181,
        /// <summary>Salvo Count</summary>
        SalvoCount = 182,
        /// <summary>Fire Delay</summary>
        FireDelay = 183,
        /// <summary>Siphon Damage</summary>
        SiphonDamage = 184,
        /// <summary>Mass Damage</summary>
        MassDamage = 185,
        /// <summary>Power Damage</summary>
        PowerDamage = 186,
        /// <summary>Transporter Assault</summary>
        TransporterAssault = 187,
        /// <summary>Transporter Assault</summary>
        TransporterAssault2 = 188,
        /// <summary>Kinetic Resistance</summary>
        KineticResistance = 189,
        /// <summary>Energy Resistance</summary>
        EnergyResistance = 190,
        /// <summary>Guided Resistance</summary>
        GuidedResistance = 191,
        /// <summary>Missile Resistance</summary>
        MissileResistance = 192,
        /// <summary>Hybrid Resistance</summary>
        HybridResistance = 193,
        /// <summary>Beam Resistance</summary>
        BeamResistance = 194,
        /// <summary>Explosive Resistance</summary>
        ExplosiveResistance = 195,
        /// <summary>Intercept Resistance</summary>
        InterceptResistance = 196,
        /// <summary>Railgun Resistance</summary>
        RailgunResistance = 197,
        /// <summary>Spacebomb Resistance</summary>
        SpacebombResistance = 198,
        /// <summary>Bomb Resistance</summary>
        BombResistance = 199,
        /// <summary>Bioweapon Resistance</summary>
        BioweaponResistance = 200,
        /// <summary>Drone Resistance</summary>
        DroneResistance = 201,
        /// <summary>Warp Resistance</summary>
        WarpResistance = 202,
        /// <summary>Torpedo Resistance</summary>
        TorpedoResistance = 203,
        /// <summary>Cannon Resistance</summary>
        CannonResistance = 204,
        /// <summary>Subspace Resistance</summary>
        SubspaceResistance = 205,
        /// <summary>PD Resistance</summary>
        PdResistance = 206,
        /// <summary>Flak Resistance</summary>
        FlakResistance = 207,
        /// <summary>AP Resistance</summary>
        ApResistance = 208,
        /// <summary>Shield Kinetic Resistance</summary>
        ShieldKineticResistance = 209,
        /// <summary>Shield Energy Resistance</summary>
        ShieldEnergyResistance = 210,
        /// <summary>Shield Explosive Resistance</summary>
        ShieldExplosiveResistance = 211,
        /// <summary>Shield Missile Resistance</summary>
        ShieldMissileResistance = 212,
        /// <summary>Shield Flak Resistance</summary>
        ShieldFlakResistance = 213,
        /// <summary>Shield Hybrid Resistance</summary>
        ShieldHybridResistance = 214,
        /// <summary>Shield Railgun Resistance</summary>
        ShieldRailgunResistance = 215,
        /// <summary>Shield Subspace Resistance</summary>
        ShieldSubspaceResistance = 216,
        /// <summary>Shield Warp Resistance</summary>
        ShieldWarpResistance = 217,
        /// <summary>Shield Beam Resistance</summary>
        ShieldBeamResistance = 218,
        /// <summary>EMP Protection</summary>
        EmpProtection = 219,
        /// <summary>EMP Protection ShipTotal</summary>
        EmpProtectionShiptotal = 220,
        /// <summary>Damage Threshold</summary>
        DamageThreshold = 221,
        /// <summary>Shield Damage Threshold</summary>
        ShieldDamageThreshold = 222,
        /// <summary>FTL Overlay</summary>
        FtlOverlay = 223,
        /// <summary>Weapons Range overlay</summary>
        WeaponsRangeOverlay = 224,
        /// <summary>Launch Shuttles</summary>
        LaunchShuttles = 225,
        /// <summary>Target Tracking</summary>
        TargetTracking = 226,
        /// <summary>Offensive Strength</summary>
        OffensiveStrength = 227,
        /// <summary>Short range order</summary>
        ShortRangeOrder = 228,
        /// <summary>Corners Game</summary>
        CornersGame = 229,
        /// <summary>Total Module Slots</summary>
        TotalModuleSlots = 230,
        /// <summary>Targets</summary>
        Targets = 231,
        /// <summary>Max Targets</summary>
        MaxTargets = 232,
        /// <summary>Max Targets 1</summary>
        MaxTargets2 = 233,
        /// <summary>Total Ship ECM</summary>
        TotalShipEcm = 234,
        /// <summary>Ship Sensor Range</summary>
        ShipSensorRange = 235,
        /// <summary>Ship Repair Rate</summary>
        ShipRepairRate = 236,
        /// <summary>Player Designs</summary>
        PlayerDesigns = 237,
        /// <summary>Explosion Damage</summary>
        ExplosionDamage = 238,
        /// <summary>Explosion Radius</summary>
        ExplosionRadius = 239,
        /// <summary>Shield Combat Recharge</summary>
        ShieldCombatRecharge = 240,
        /// <summary>Complexity</summary>
        Complexity = 241,
        /// <summary>Projectiles</summary>
        Projectiles = 242,
        /// <summary>Total Weapons Power Usage per second when firing</summary>
        TotalWeaponsPowerUsagePer = 243,
        /// <summary>Weapons Peak Power drain during full beam duration</summary>
        WeaponsPeakPowerDrainDuring = 244,
        /// <summary>Weapons Peak Power Time during full beam duration</summary>
        WeaponsPeakPowerTimeDuring = 245,
        /// <summary>Symmetric Ship Design Mode</summary>
        SymmetricShipDesignMode = 246,
        /// <summary>Powered Command Module</summary>
        PoweredCommandModule = 247,
        /// <summary>Empty slots</summary>
        EmptySlots = 248,
        /// <summary>Injury level inflicted to invading troops</summary>
        InjuryLevelInflictedToInvading = 249,
        /// <summary>Planet's space offense</summary>
        PlanetsSpaceOffense = 250,
        /// <summary>Troop Weapon Range</summary>
        TroopWeaponRange = 251,
        /// <summary>Allow Inter-Empire Trade</summary>
        AllowInterempireTrade = 252,
        /// <summary>Define Trade Routes</summary>
        DefineTradeRoutes = 253,
        /// <summary>Population vs. Max Population</summary>
        PopulationVsMaxPopulation = 254,
        /// <summary>Treasury Goal Projection</summary>
        TreasuryGoalProjection = 255,
        /// <summary>Relative Strength</summary>
        RelativeStrength = 256,
        /// <summary>Ship Total Shield Amp</summary>
        ShipShieldAmplify = 257,
        /// <summary>Module Shield Amp</summary>
        ModuleShieldAmplify = 258,
        /// <summary>Regeneration</summary>
        SelfRegeneration = 259,
        /// <summary>Habitable Tiles</summary>
        NumhabitableTiles = 260,
        /// <summary>Pop Per Tile</summary>
        PopPerTile = 261,
        /// <summary>Biosphered Pop</summary>
        BiospheredPopPotential = 262,
        /// <summary>Terraformed Pop</summary>
        TerraformedPopPotential = 263,
        /// <summary>Planetary Shield Strength</summary>
        PlanetaryShieldStr = 264,
        /// <summary>Planet Panel</summary>
        PlanetPanel = 265,
        /// <summary>Big Clusters</summary>
        BigClusters = 266,
        /// <summary>Small Clusters</summary>
        SmallClusters = 267,
        /// <summary>Hangar Size</summary>
        HangarSize = 268,
        /// <summary>Terminal Phase Range</summary>
        TerminalPhaseRange = 269,
        /// <summary>Terminal Phase Speed</summary>
        TerminalPhaseSpeed = 270,
        /// <summary>Delayed Ignition</summary>
        DelayedIgnition = 271,
        /// <summary>MIRV</summary>
        Mirv = 272,
        /// <summary>Imprecision</summary>
        Imprecision = 273,
        /// <summary>Accuracy</summary>
        Accuracy = 274,
        /// <summary>TargetTracking</summary>
        Targettracking = 275,
        /// <summary>Armor Pen</summary>
        ArmorPen = 276,
        /// <summary>Explosion Radius</summary>
        ExplosionRadius2 = 277,
        /// <summary>Number Of Colonists</summary>
        NumberOfColonists = 278,
        /// <summary>Colony Rank</summary>
        ColonyRank = 279,
        /// <summary>Civilian Budget</summary>
        CivilianBudget = 280,
        /// <summary>Ground Defense Budget</summary>
        GroundDefenseBudget = 281,
        /// <summary>Orbitals Budget</summary>
        OrbitalsBudget = 282,
        /// <summary>Civilian Expense</summary>
        CivilianExpense = 283,
        /// <summary>Ground Defense Expense</summary>
        GroundDefenseExpense = 284,
        /// <summary>Orbitals Expense</summary>
        OrbitalsExpense = 285,
    }
}
