// ReSharper disable UnusedMember.Global
// ReSharper disable IdentifierTypo
// ReSharper disable CommentTypo
namespace Ship_Game
{
    /// <summary>
    /// This file was auto-generated by SDGameTextToEnum.exe
    /// </summary>
    public enum GameTips
    {
        /// <summary>ShipWillMakeHeadonAttack: Attack Runs Order</summary>
        AttackRunsOrder = 1,
        /// <summary>ShipWillRotateSoThat: Artillery Order</summary>
        ArtilleryOrder = 2,
        /// <summary>ShipWillManeuverToKeep: Orbit Left Order</summary>
        OrbitLeftOrder = 3,
        /// <summary>ShipWillManeuverToKeep2: Orbit Right Order</summary>
        OrbitRightOrder = 4,
        /// <summary>ShipWillAttemptToMaintain: Maintain Order</summary>
        MaintainOrder = 5,
        /// <summary>ShipWillAvoidEngagingIn: Evade Order</summary>
        EvadeOrder = 6,
        /// <summary>AMeasureOfHowCooperative: Assist Slider</summary>
        AssistSlider = 7,
        /// <summary>AMeasureOfHowProtective: Defender Slider</summary>
        DefenderSlider = 8,
        /// <summary>AMeasureOfHowOpportunistic: Vulture Slider</summary>
        VultureSlider = 9,
        /// <summary>TheWeightGivenToTargeting: Armor Slider</summary>
        ArmorSlider = 10,
        /// <summary>TheWeightGivenToTargeting2: Shielded Slider</summary>
        ShieldedSlider = 11,
        /// <summary>TheWeightGivenToTargeting3: DPS Slider</summary>
        DpsSlider = 12,
        /// <summary>DefinesTheAreaInWhich: Operational Radius</summary>
        OperationalRadius = 13,
        /// <summary>DeterminesWhetherAShipPrefers: Size Slider</summary>
        SizeSlider = 14,
        /// <summary>AllowsYouToCustomizeAn: Define AO</summary>
        DefineAo = 15,
        /// <summary>ManualTradeOrdersThisFreighter2: Trade Food</summary>
        TradeFood = 16,
        /// <summary>ManualTradeOrdersThisFreighter3: Trade Production</summary>
        TradeProduction = 17,
        /// <summary>SendTroopsToThisShip: Send_Troops_Supply</summary>
        ShieldToggle = 18,
        /// <summary>WhenActiveAllAvailableFighters: Launch Fighters</summary>
        LaunchFighters = 19,
        /// <summary>IndicatesHowMuchFoodThis: Food Icon</summary>
        FoodIcon = 20,
        /// <summary>APlanetsMineralRichnessDirectly: Production Icon</summary>
        ProductionIcon = 21,
        /// <summary>IndicatesHowMuchResearchThis: Research Icon</summary>
        ResearchIcon = 22,
        /// <summary>APlanetsMineralRichnessDirectly: Ore Icon</summary>
        OreIcon = 23,
        /// <summary>MarkThisPlanetForColonization: Mark for Colonization</summary>
        MarkForColonization = 24,
        /// <summary>CancelTheColonizationMissionThat: UnMark for Colonization</summary>
        UnmarkForColonization = 25,
        /// <summary>IndicatesThatYourEmpireHas: Flag indicating marked</summary>
        FlagIndicatingMarked = 26,
        /// <summary>IndicatesThisShipsCurrentPower: Ship Selector Power</summary>
        ShipSelectorPower = 27,
        /// <summary>IndicatesTheTotalPowerOf: Ship Selector Shields</summary>
        ShipSelectorShields = 28,
        /// <summary>IndicatesThisShipsCurrentStores: Ship Selector Ordnance</summary>
        ShipSelectorOrdnance = 29,
        /// <summary>IndicatesThisShipsCurrentDefense: Ship Selector Defense</summary>
        ShipSelectorDefense = 30,
        /// <summary>IndicatesThisColonysTotalStrength: Planet Selector Defense</summary>
        PlanetSelectorDefense = 31,
        /// <summary>OrdersAllBombequippedShipsIn: orbital asset bombard</summary>
        OrbitalAssetBombard = 32,
        /// <summary>IndicatesThisUnitsGroundCombat: unit defense</summary>
        UnitDefense = 33,
        /// <summary>IndicatesThisUnitsCombatEffectiveness: soft attack</summary>
        SoftAttack = 34,
        /// <summary>IndicatesThisUnitsCombatEffectiveness2: hard attack</summary>
        HardAttack = 35,
        /// <summary>OpensAPanelDisplayingAny: land troops button</summary>
        LandTroopsButton = 36,
        /// <summary>IndicatesTheNumberOfTroops: ship troop capacity</summary>
        ShipTroopCapacity = 37,
        /// <summary>ThisRepresentsHowFullyYour: Intelligence Penetration</summary>
        IntelligencePenetration = 38,
        /// <summary>TheMoreYouSpendOn: Intelligence Budget</summary>
        IntelligenceBudget = 39,
        /// <summary>YourCounterespionageBudgetReducesThe: Counterspy Budget</summary>
        CounterspyBudget = 40,
        /// <summary>RandomlyPlacesAnAgentOn: Plant mole</summary>
        PlantMole = 41,
        /// <summary>ActivateYourIntelligenceAssetsTo: Discover Plot</summary>
        DiscoverPlot = 42,
        /// <summary>UseYourAgentsToStir: damage relations</summary>
        DamageRelations = 43,
        /// <summary>PutAnAgentInPlace: Plant saboteur</summary>
        PlantSaboteur = 44,
        /// <summary>ActivatesAllSaboteursSimultaneouslyThe: activate saboteur</summary>
        ActivateSaboteur = 45,
        /// <summary>WillStealARandomTechnology: steal technology</summary>
        StealTechnology = 46,
        /// <summary>ThisIndicatesHowMuchA: trust</summary>
        Trust = 47,
        /// <summary>ThisIndicatesHowAngryA: anger</summary>
        Anger = 48,
        /// <summary>ThisIndicatesHowMuchA2: fear</summary>
        Fear = 49,
        /// <summary>ClickToRushProductionFrom: Rush Production</summary>
        RushProduction = 50,
        /// <summary>AddThisItemToThe: Add to Q</summary>
        AddToQ = 51,
        /// <summary>EditThisShipInThe: Edit ship</summary>
        EditShip = 52,
        /// <summary>CancelProductionAndRemoveThis: Cancel Production</summary>
        CancelProduction = 53,
        /// <summary>OpensTheDeepSpaceBuilding: DSBW</summary>
        Dsbw = 54,
        /// <summary>OpensTheShipsListWhich: Ships List</summary>
        ShipsList = 55,
        /// <summary>OpensPlanetReconnaissancePanel: Planets List</summary>
        PlanetsList = 56,
        /// <summary>ZoomsToYourCurrentlySelected: Home</summary>
        Home = 57,
        /// <summary>ZoomOutToTheGalaxy: Zoom out</summary>
        ZoomOut = 58,
        /// <summary>OpensTheAutomationPanelWhich: Automation</summary>
        Automation = 59,
        /// <summary>OpensTheFleetsScreenWhich: Fleets</summary>
        Fleets = 60,
        /// <summary>ViewPlanetDetails: View Planet</summary>
        ViewPlanet = 61,
        /// <summary>OpenTheGroundAssaultView: View Tactical</summary>
        ViewTactical = 62,
        /// <summary>ClickToMoveUpIn: Queue up</summary>
        QueueUp = 63,
        /// <summary>ClickToMoveDownIn: Queue down</summary>
        QueueDown = 64,
        /// <summary>ShipWillAttemptToHold: Hold Position Order</summary>
        HoldPositionOrder = 65,
        /// <summary>TaxesAreCollectedFromYour: Taxes</summary>
        Taxes = 66,
        /// <summary>LaunchThisTroopIntoOrbit: Launch Troop</summary>
        LaunchTroop = 67,
        /// <summary>IndicatesAShipsExperienceLevel: Experience</summary>
        Experience = 68,
        /// <summary>LocksThisSliderPreventingThe: Lock</summary>
        Lock = 69,
        /// <summary>FoodIsEatenByYour: Food</summary>
        Food = 70,
        /// <summary>ProductionIsRequiredForThe: prod</summary>
        Prod = 71,
        /// <summary>ResearchPointsAreAddedInto: Res</summary>
        Res = 72,
        /// <summary>IndicatesTheAmountOfFood: prod</summary>
        Prod2 = 73,
        /// <summary>IndicatesTheAmountOfProduction: Res</summary>
        Res2 = 74,
        /// <summary>AColonysPopulationIsA: Population</summary>
        Population = 75,
        /// <summary>OpensColonyOverviewScreen: view colony</summary>
        ViewColony = 76,
        /// <summary>YourPeopleAreCyberneticAnd: cybernetic food</summary>
        CyberneticFood = 77,
        /// <summary>DeleteThisShipDesign: delete design</summary>
        DeleteDesign = 78,
        /// <summary>AShipsTotalMassDetermines: ship mass</summary>
        ShipMass = 79,
        /// <summary>AModulesHealthRepresentsHow: mod health</summary>
        ModHealth = 80,
        /// <summary>IndicatesHowMuchPowerThis: mod health</summary>
        ModHealth2 = 81,
        /// <summary>IndicatesTheMaximumRangeOf: mod health</summary>
        ModHealth3 = 82,
        /// <summary>IndicatesTheMaximumAmountOf: wpn damage</summary>
        WpnDamage = 83,
        /// <summary>IndicatesTheProductionCostOf: mod cost</summary>
        ModCost = 84,
        /// <summary>IndicatesTheDistanceAProjectile: proj speed</summary>
        ProjSpeed = 85,
        /// <summary>IndicatesTheMaximumDamagePer: DPS</summary>
        Dps = 86,
        /// <summary>TheAmountOfPowerThis: beam cps</summary>
        BeamCps = 87,
        /// <summary>AWeaponMayOnlyFire: field of fire</summary>
        FieldOfFire = 88,
        /// <summary>IndicatesTheAmountOfOrdnance: ord per shot</summary>
        OrdPerShot = 89,
        /// <summary>IndicatesTheAmountOfPower: pwr per shot</summary>
        PwrPerShot = 90,
        /// <summary>IndicatesTheAmountOfThrust: thrust</summary>
        Thrust = 91,
        /// <summary>IndicatesTheAmountOfThrust2: warp thrust</summary>
        WarpThrust = 92,
        /// <summary>IndicatesTheHitpointsOfThis: shield hp</summary>
        ShieldHp = 93,
        /// <summary>IndicatesTheProtectiveRadiusOf: shield rad</summary>
        ShieldRad = 94,
        /// <summary>IndicatesTheNumberOfHitpoints: shield regen</summary>
        ShieldRegen = 95,
        /// <summary>IndicatesTheAdditionalSensorRange: sensor range</summary>
        SensorRange = 96,
        /// <summary>IndicatesTheBonusToOutofcombat: repair rate</summary>
        RepairRate = 97,
        /// <summary>HangarsAreCapableOfSustaning: hangar</summary>
        Hangar = 98,
        /// <summary>IndicatesTheTotalProductionValue: ship cost</summary>
        ShipCost = 99,
        /// <summary>IndicatesTheMaximumAmountOf2: ship power</summary>
        ShipPower = 100,
        /// <summary>IndicatesTheNetPowerFlow: ship powerdraw</summary>
        ShipPowerdraw = 101,
        /// <summary>IndicatesTheNetPowerFlow2: ship warp powerdraw</summary>
        ShipWarpPowerdraw = 102,
        /// <summary>IndicatesTheTotalHitpointsOf: total hp</summary>
        TotalHp = 103,
        /// <summary>IndicatesTheTotalHitpointsOf2: shield hp</summary>
        ShieldHp2 = 104,
        /// <summary>IndicatesTheDistanceThisShip: speed sublight</summary>
        SpeedSublight = 105,
        /// <summary>IndicatesTheDistanceThisShip2: speed warp</summary>
        SpeedWarp = 106,
        /// <summary>IndicatesTheNumberOfDegrees: turn</summary>
        Turn = 107,
        /// <summary>IndicatesTheMaximumAmountOf3: ord</summary>
        Ord = 108,
        /// <summary>IndicatesTheTotalCargoSpace: cargo</summary>
        Cargo = 109,
        /// <summary>IndicatesTheAmountOfEmp: emp</summary>
        Emp = 110,
        /// <summary>InTheAscensionGameMode: ascension</summary>
        Ascension = 111,
        /// <summary>InTheSandboxGameMode: sandbox</summary>
        Sandbox = 112,
        /// <summary>IndicatesHowManyUnitsOf: food carry</summary>
        FoodCarry = 113,
        /// <summary>IndicatesHowManyUnitsOf2: prod carry</summary>
        ProdCarry = 114,
        /// <summary>IndicatesHowManyUnitsOf3: colo carry</summary>
        ColoCarry = 115,
        /// <summary>IndicatesThatThisShipIs: EMP disabled</summary>
        EmpDisabled = 116,
        /// <summary>IndicatesThatThisShipCannot: inhibited</summary>
        Inhibited = 117,
        /// <summary>IndicatesThatThisShipIs2: boarding</summary>
        Boarding = 118,
        /// <summary>IndicatesThatGroundCombatIs: ground com</summary>
        GroundCom = 119,
        /// <summary>IndicatesThatAFriendlyAgent: spy</summary>
        Spy = 120,
        /// <summary>IndicatesThatAnAnomalyWas: anomaly</summary>
        Anomaly = 121,
        /// <summary>IndicatesThatSpaceCombatIs: space combat</summary>
        SpaceCombat = 122,
        /// <summary>IndicatesThatHostileForcesWere: enemy here</summary>
        EnemyHere = 123,
        /// <summary>IndicatesTheAmountOfOrdnance2: ord cap added</summary>
        OrdCapAdded = 124,
        /// <summary>IncreasingTheScaleOfA: scale</summary>
        Scale = 125,
        /// <summary>TheGamesPaceModifiesThe: pacing</summary>
        Pacing = 126,
        /// <summary>IndicatesThisTroopsExperienceLevel: troop level</summary>
        TroopLevel = 127,
        /// <summary>YouCurrentlyHaveAPeace: can't declare war peace treaty</summary>
        CantDeclareWarPeaceTreaty = 128,
        /// <summary>ANonaggressionPactIsA: Non Aggression</summary>
        NonAggression = 129,
        /// <summary>AnOpenBordersTreatyWill: open borders</summary>
        OpenBorders = 130,
        /// <summary>PeaceTreatiesLastForTurns: Peace Treaty</summary>
        PeaceTreaty = 131,
        /// <summary>TradeTreatiesCreateWealthFor: trade Treaty</summary>
        TradeTreaty = 132,
        /// <summary>AlliancesAreSeriousCommitmentsBetween: alliance Treaty</summary>
        AllianceTreaty = 133,
        /// <summary>TogglesTheWeaponFireArc: fire arcs</summary>
        FireArcs = 134,
        /// <summary>IndicatesTheDistanceThisShip3: Warp Speed</summary>
        WarpSpeed = 135,
        /// <summary>OrdersThisShipToExplore: Explore</summary>
        Explore = 136,
        /// <summary>ManualTradeOrdersThisFreighter: pass tran</summary>
        PassTran = 137,
        /// <summary>IndicatesThatAnAnomalyHas: pass tran</summary>
        PassTran2 = 138,
        /// <summary>TheNetAmountOfFood: empire screen food</summary>
        EmpireScreenFood = 139,
        /// <summary>TheNetAmountOfProduction: empire screen prod</summary>
        EmpireScreenProd = 140,
        /// <summary>TheNetAmountOfResearch: empire screen res</summary>
        EmpireScreenRes = 141,
        /// <summary>TheNetIncomeOfThis: empire screen money</summary>
        EmpireScreenMoney = 142,
        /// <summary>IndicatesTheCombatStrengthAdded: boarding defense</summary>
        BoardingDefense = 143,
        /// <summary>IndicatesTheWarpInhibitionRange: inhib</summary>
        Inhib = 144,
        /// <summary>IndicatesTheAmountOfPower2: power store max</summary>
        PowerStoreMax = 145,
        /// <summary>ClickToToggleWhetherThis: recall fighters</summary>
        RecallFighters = 146,
        /// <summary>IndicatesAnyBonusOrPenalty: vs armor</summary>
        VsArmor = 147,
        /// <summary>IndicatesTheAmountOfRotational: rot thrust</summary>
        RotThrust = 148,
        /// <summary>OrdersSelectedShipOrShips: resupply</summary>
        Resupply = 149,
        /// <summary>OrdersThisShipOrShips: empire defense</summary>
        EmpireDefense = 150,
        /// <summary>OrderTheseShipsToBegin: trade</summary>
        Trade = 151,
        /// <summary>OrderTheseShipsToBegin2: trade</summary>
        Trade2 = 152,
        /// <summary>OrderTheseShipsToBegin2: trade</summary>
        Trade3 = 153,
        /// <summary>IndicatesTheChanceOfEcm: ECM value</summary>
        EcmValue = 154,
        /// <summary>IndicatesTheResistanceOfThis: ECM Resistance value</summary>
        EcmResistanceValue = 155,
        /// <summary>IndicatesTheMaximumDurationFor: Beam Duration</summary>
        BeamDuration = 156,
        /// <summary>OrderShipBackToThe: Scrap Ship</summary>
        ScrapShip = 157,
        /// <summary>OrderShipRefit: Refit Ship</summary>
        RefitShip = 158,
        /// <summary>ShipWillMoveWithinMaximum: Broadside Port</summary>
        BroadsidePort = 159,
        /// <summary>ShipWillMoveWithinMaximum2: Broadside Starboard</summary>
        BroadsideStarboard = 160,
        /// <summary>IndicatesAShipsExperienceLevel2: New Experience</summary>
        NewExperience = 161,
        /// <summary>IndicatesTheAmountOfOrdnance3: Ordance recovered per sec.</summary>
        OrdanceRecoveredPerSec = 162,
        /// <summary>IndicatesTheMaximumTimeIn: Seconds until out of power or INFinite</summary>
        SecondsUntilOutOfPower = 163,
        /// <summary>IndicatesTheMaximumTimeIn2: Seconds until out of ordnance or INFinite</summary>
        SecondsUntilOutOfOrdnance = 164,
        /// <summary>InTheCapitalEliminationGame: Elimination Game mode</summary>
        EliminationGameMode = 165,
        /// <summary>IndicatesTheMaximumAmountOf4: Repair Beam</summary>
        RepairBeam = 166,
        /// <summary>IndicatesSensorBonusAddedBy: Repair Beam</summary>
        RepairBeam2 = 167,
        /// <summary>IndicatesTheRangeOfThis: Transporter Range</summary>
        TransporterRange = 168,
        /// <summary>IndicatesThePowerUsedBy: Transporter Power</summary>
        TransporterPower = 169,
        /// <summary>IndicatesTheDelayBetweenTransports: Transporter Time</summary>
        TransporterTime = 170,
        /// <summary>IndicatesTheAmountOfOrdnance4: Transporter Ordnance</summary>
        TransporterOrdnance = 171,
        /// <summary>IndicatesTheNumberOfTroops2: Transporter Troop Landing</summary>
        TransporterTroopLanding = 172,
        /// <summary>IndicatesTheNumberOfTroops3: Troop Capacity</summary>
        TroopCapacity = 173,
        /// <summary>IndicatesTheAmountTroopsAre: Troop Heal</summary>
        TroopHeal = 174,
        /// <summary>IndicatesTheCreditsPerTick: Shipyard Upkeep</summary>
        ShipyardUpkeep = 175,
        /// <summary>IndicatesThisShipsMaximumSustained: FTL Timer</summary>
        FtlTimer = 176,
        /// <summary>IndicatesTheTimeInSeconds: FTL Spool</summary>
        FtlSpool = 177,
        /// <summary>TheEffectivePowerDrainOf: Module power draw at warp</summary>
        ModulePowerDrawAtWarp = 178,
        /// <summary>TheNumberOfTroopsThis: Module troop capacity</summary>
        ModuleTroopCapacity = 179,
        /// <summary>IndicatesTheTotalComplementOf: Ship troop capacity</summary>
        ShipTroopCapacity2 = 180,
        /// <summary>RandomChanceThisWeaponWill: Weapon Shield Pen</summary>
        WeaponShieldPen = 181,
        /// <summary>ThisWeaponsFireASalvo: Salvo Count</summary>
        SalvoCount = 182,
        /// <summary>TimeBetweenShots: Fire Delay</summary>
        FireDelay = 183,
        /// <summary>IndicatesTheAmountOfShields: Siphon Damage</summary>
        SiphonDamage = 184,
        /// <summary>IndicatesTheAmountOfDrag: Mass Damage</summary>
        MassDamage = 185,
        /// <summary>IndicatesTheAmountOfPower3: Power Damage</summary>
        PowerDamage = 186,
        /// <summary>IndicatesTheNumberOfTroops4: Transporter Assault</summary>
        TransporterAssault = 187,
        /// <summary>TheDurationABeamWill: Transporter Assault</summary>
        TransporterAssault2 = 188,
        /// <summary>IndicatesResistanceToKinetictypeDamage: Kinetic Resistance</summary>
        KineticResistance = 189,
        /// <summary>IndicatesResistanceToEnergyWeapon: Energy Resistance</summary>
        EnergyResistance = 190,
        /// <summary>IndicatesResistanceToGuidedWeapon: Guided Resistance</summary>
        GuidedResistance = 191,
        /// <summary>IndicatesResistanceToMissileWeapon: Missile Resistance</summary>
        MissileResistance = 192,
        /// <summary>IndicatesResistanceToHybridWeapon: Hybrid Resistance</summary>
        HybridResistance = 193,
        /// <summary>IndicatesResistanceToBeamWeapon: Beam Resistance</summary>
        BeamResistance = 194,
        /// <summary>IndicatesResistanceToExplosiveDamage: Explosive Resistance</summary>
        ExplosiveResistance = 195,
        /// <summary>IndicatesResistanceToInterceptableWeapon: Intercept Resistance</summary>
        InterceptResistance = 196,
        /// <summary>IndicatesResistanceToRailgunWeapon: Railgun Resistance</summary>
        RailgunResistance = 197,
        /// <summary>IndicatesResistanceToSpatialBomb: Spacebomb Resistance</summary>
        SpacebombResistance = 198,
        /// <summary>IndicatesResistanceToBombardmentWeapon: Bomb Resistance</summary>
        BombResistance = 199,
        /// <summary>IndicatesResistanceToBiologicalWeapon: Bioweapon Resistance</summary>
        BioweaponResistance = 200,
        /// <summary>IndicatesResistanceToDroneWeapon: Drone Resistance</summary>
        DroneResistance = 201,
        /// <summary>IndicatesResistanceToWarpWeapon: Warp Resistance</summary>
        WarpResistance = 202,
        /// <summary>IndicatesResistanceToTorpedoWeapon: Torpedo Resistance</summary>
        TorpedoResistance = 203,
        /// <summary>IndicatesResistanceToCannonWeapon: Cannon Resistance</summary>
        CannonResistance = 204,
        /// <summary>IndicatesResistanceToSubspaceWeapon: Subspace Resistance</summary>
        SubspaceResistance = 205,
        /// <summary>IndicatesResistanceToPdWeapon: PD Resistance</summary>
        PdResistance = 206,
        /// <summary>IndicatesResistanceToFlakWeapon: Flak Resistance</summary>
        FlakResistance = 207,
        /// <summary>IndicatesResistanceToArmourPiercing: AP Resistance</summary>
        ApResistance = 208,
        /// <summary>IndicatesShieldBubblesResistanceTo: Shield Kinetic Resistance</summary>
        ShieldKineticResistance = 209,
        /// <summary>IndicatesShieldBubblesResistanceTo2: Shield Energy Resistance</summary>
        ShieldEnergyResistance = 210,
        /// <summary>IndicatesShieldBubblesResistanceTo3: Shield Explosive Resistance</summary>
        ShieldExplosiveResistance = 211,
        /// <summary>IndicatesShieldBubblesResistanceTo4: Shield Missile Resistance</summary>
        ShieldMissileResistance = 212,
        /// <summary>IndicatesShieldBubblesResistanceTo5: Shield Flak Resistance</summary>
        ShieldFlakResistance = 213,
        /// <summary>IndicatesShieldBubblesResistanceTo6: Shield Hybrid Resistance</summary>
        ShieldHybridResistance = 214,
        /// <summary>IndicatesShieldBubblesResistanceTo7: Shield Railgun Resistance</summary>
        ShieldRailgunResistance = 215,
        /// <summary>IndicatesShieldBubblesResistanceTo8: Shield Subspace Resistance</summary>
        ShieldSubspaceResistance = 216,
        /// <summary>IndicatesShieldBubblesResistanceTo9: Shield Warp Resistance</summary>
        ShieldWarpResistance = 217,
        /// <summary>IndicatesShieldBubblesResistanceTo10: Shield Beam Resistance</summary>
        ShieldBeamResistance = 218,
        /// <summary>IndicatesTheAmountOfEmp2: EMP Protection</summary>
        EmpProtection = 219,
        /// <summary>TheTotalEmpProtectionOf: EMP Protection ShipTotal</summary>
        EmpProtectionShiptotal = 220,
        /// <summary>WeaponsWhichDoLessDamage: Damage Threshold</summary>
        DamageThreshold = 221,
        /// <summary>WeaponsWhichDoLessDamage2: Shield Damage Threshold</summary>
        ShieldDamageThreshold = 222,
        /// <summary>FtlOverlayVisualisesSubspaceProjection: FTL Overlay</summary>
        FtlOverlay = 223,
        /// <summary>WeaponsRangeOverlayVisualisesShips: Weapons Range overlay</summary>
        WeaponsRangeOverlay = 224,
        /// <summary>TogglesWhetherThisShipsAssault: Launch Shuttles</summary>
        LaunchShuttles = 225,
        /// <summary>ThisIsABonusTo: Target Tracking</summary>
        TargetTracking = 226,
        /// <summary>EstimatedOffensiveStrengthOfThe: Offensive Strength</summary>
        OffensiveStrength = 227,
        /// <summary>ShipWillRotateSoThat2: Short range order</summary>
        ShortRangeOrder = 228,
        /// <summary>CornersIsARaceMatch: Corners Game</summary>
        CornersGame = 229,
        /// <summary>TheTotalNumberOfModule: Total Module Slots</summary>
        TotalModuleSlots = 230,
        /// <summary>ThisValueRepresentsTheComplexity: Targets</summary>
        Targets = 231,
        /// <summary>ThisIsTheTotalNumber: Max Targets</summary>
        MaxTargets = 232,
        /// <summary>ThisIsTheTotalNumber2: Max Targets 1</summary>
        MaxTargets2 = 233,
        /// <summary>ThisIsTheTotalElectronic: Total Ship ECM</summary>
        TotalShipEcm = 234,
        /// <summary>ThisIsTheMaximumSensor: Ship Sensor Range</summary>
        ShipSensorRange = 235,
        /// <summary>ThisIsThisShipsSelfrepair: Ship Repair Rate</summary>
        ShipRepairRate = 236,
        /// <summary>ToggleToDisplayOnlyPlayerdesigned: Player Designs</summary>
        PlayerDesigns = 237,
        /// <summary>TheDamageCausedToNearby: Explosion Damage</summary>
        ExplosionDamage = 238,
        /// <summary>TheDamageRadiusOfThis: Explosion Radius</summary>
        ExplosionRadius = 239,
        /// <summary>ThisShieldCanRechargeEven: Shield Combat Recharge</summary>
        ShieldCombatRecharge = 240,
        /// <summary>TheMoreComplexTheModule: Complexity</summary>
        Complexity = 241,
        /// <summary>ThisWeaponFiresMoreThan: Projectiles</summary>
        Projectiles = 242,
        /// <summary>ThisIndicatesThatThereIs2: Total Weapons Power Usage per second when firing</summary>
        TotalWeaponsPowerUsagePer = 243,
        /// <summary>ThisIndicatesThatThereIs: Weapons Peak Power drain during full beam duration</summary>
        WeaponsPeakPowerDrainDuring = 244,
        /// <summary>TheTotalTimeTheShip: Weapons Peak Power Time during full beam duration</summary>
        WeaponsPeakPowerTimeDuring = 245,
        /// <summary>YouCanSwitchFromNormal: Symmetric Ship Design Mode</summary>
        SymmetricShipDesignMode = 246,
        /// <summary>AFunctionalShipNeedsA: Powered Command Module</summary>
        PoweredCommandModule = 247,
        /// <summary>InOrderToCompleteYour: Empty slots</summary>
        EmptySlots = 248,
        /// <summary>EveryTroopInvadingThisPlanet: Injury level inflicted to invading troops</summary>
        InjuryLevelInflictedToInvading = 249,
        /// <summary>ThePlanetsSpaceOffenseVs: Planet's space offense</summary>
        PlanetsSpaceOffense = 250,
        /// <summary>IndicatesTheTileRangeThis: Troop Weapon Range</summary>
        TroopWeaponRange = 251,
        /// <summary>ManualTradeAllowSelectedFreighters: Allow Inter-Empire Trade</summary>
        AllowInterempireTrade = 252,
        /// <summary>ChooseAListOfPlanets: Define Trade Routes</summary>
        DefineTradeRoutes = 253,
        /// <summary>PopulationInBillionsVsMax: Population vs. Max Population</summary>
        PopulationVsMaxPopulation = 254,
        /// <summary>TreasuryGoalIsTheTarget: Treasury Goal Projection</summary>
        TreasuryGoalProjection = 255,
        /// <summary>ThisIsTheStrengthOf: Relative Strength</summary>
        RelativeStrength = 256,
        /// <summary>EachOfTheShipShields: Ship Total Shield Amp</summary>
        ShipShieldAmplify = 257,
        /// <summary>WhenPoweredThisAmplifiesThe: Module Shield Amp</summary>
        ModuleShieldAmplify = 258,
        /// <summary>ThisModuleHasSelfRegeneration: Regeneration</summary>
        SelfRegeneration = 259,
        /// <summary>ThisIndicatesHowManyTiles: Habitable Tiles</summary>
        NumhabitableTiles = 260,
        /// <summary>ThisIndicatesHowMuchPopulation: Pop Per Tile</summary>
        PopPerTile = 261,
        /// <summary>ThisIndicatesWhatWouldThe: Biosphered Pop</summary>
        BiospheredPopPotential = 262,
        /// <summary>ThisIndicatesWhatWouldThe2: Terraformed Pop</summary>
        TerraformedPopPotential = 263,
        /// <summary>IndicatesTheCurrentStrengthOf: Planetary Shield Strength</summary>
        PlanetaryShieldStr = 264,
        /// <summary>PlanetTypeAndRichnessThe: Planet Panel</summary>
        PlanetPanel = 265,
        /// <summary>EachEmpireStartsInA: Big Clusters</summary>
        BigClusters = 266,
        /// <summary>TheGalaxyWillBeConsisted: Small Clusters</summary>
        SmallClusters = 267,
        /// <summary>ThisIsTheMaximumNumber: Hangar Size</summary>
        HangarSize = 268,
        /// <summary>ThisMissileHasTerminalPhase: Terminal Phase Range</summary>
        TerminalPhaseRange = 269,
        /// <summary>ThisIsTheSpeedThe: Terminal Phase Speed</summary>
        TerminalPhaseSpeed = 270,
        /// <summary>ThisMissileHasDelayedIgnition: Delayed Ignition</summary>
        DelayedIgnition = 271,
        /// <summary>ThisWeaponHasMirvMeaning: MIRV</summary>
        Mirv = 272,
        /// <summary>MaximumImprecisionAngleInDegrees: Imprecision</summary>
        Imprecision = 273,
        /// <summary>WeaponTargetError: Accuracy</summary>
        Accuracy = 274,
        /// <summary>FireControlSystemsOrFcs: TargetTracking</summary>
        Targettracking = 275,
        /// <summary>ArmorPenetrationEnablesThisWeapon: Armor Pen</summary>
        ArmorPen = 276,
        /// <summary>TheRadiusOfTheProjectiles: Explosion Radius</summary>
        ExplosionRadius2 = 277,
        /// <summary>ProsperInTerranWorldsAnd: Number Of Colonists</summary>
        NumberOfColonists = 278,
        /// <summary>TheRankOfTheColony: Colony Rank</summary>
        ColonyRank = 279,
        /// <summary>CivilianBuildingsExpenditurebudgetInByc: Civilian Budget</summary>
        CivilianBudget = 280,
        /// <summary>GroundDefenseBuildingsExpenditurebudgetIn: Ground Defense Budget</summary>
        GroundDefenseBudget = 281,
        /// <summary>OrbitalsExpenditurebudgetInByc: Orbitals Budget</summary>
        OrbitalsBudget = 282,
        /// <summary>CivilianBuildingsExpenditureInByc: Civilian Expense</summary>
        CivilianExpense = 283,
        /// <summary>GroundDefenseBuildingsExpenditureIn: Ground Defense Expense</summary>
        GroundDefenseExpense = 284,
        /// <summary>OrbitalsExpenditureInByc: Orbitals Expense</summary>
        OrbitalsExpense = 285,
    }
}
